theme: jekyll-material-theme

# url: https://www.cc.gatech.edu
url: http://localhost:4000/
baseurl: #/~jabernethy9

syntax_highlighting: true # include the css for syntax highlighting

scholar:
  style: apa
  bibliography: references.bib
  bibliography_template: bibliography
  sort_by: year,month
  order: descending
  group_by: type
  type_names: { inproceedings: Conference and Workshop Papers, misc: Open Problems, article: Journal Papers, techreport: Technical Report }

markdown: kramdown
mathjax: true
permalink: pretty
collections:
  - sections

dir_pubs: pdf/publications
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier

